### ISSUE TITLE
JSON controller outputs exception and stack trace

### ISSUE THREAD

**Issue by Sukasa** [Rinsen/WebServer#3] opened 2015-04-02 01:28 UTC
I'm trying to use the framework as part of a web GUI, but using the Json output is not working; it just outputs an error.  The error displayed in the browser is:

```
Internal server error

Exception
Message:
Exception was thrown: System.ArgumentException
Stack Trace:
System.Reflection.MethodBase::Invoke
Rinsen.WebServer.Serializers.JsonSerializer::Serialize
Rinsen.WebServer.Serializers.JsonSerializer::Serialize
Rinsen.WebServer.Controller::SetJsonResult
Reflow_Oven_Controller.Web_GUI.DataController::Index
System.Reflection.MethodBase::Invoke
Rinsen.WebServer.HttpApplicationHandler::Execute
Rinsen.WebServer.RequestResponseHandler::CreateResponse
Rinsen.WebServer.RequestResponseHandler::ProcessRequest
Rinsen.WebServer.SocketListener::ProcessRequest
Rinsen.WebServer.SocketListener::ProcessClientRequest
Rinsen.WebServer.SocketListener::StartListening
Rinsen.WebServer.ServerBase::MyThreadStart
Rinsen.WebServer.ServerBase::<StartServer>b__0
```

And the entire code for my Json controller is:
    using System;
    using Microsoft.SPOT;
    using Rinsen.WebServer;

```
namespace Reflow_Oven_Controller.Web_GUI
{
    class DataController : Controller
    {
        public void Index()
        {
            var Data = new JsonData
            {
                OvenTemperature = OvenController.OvenTemperature,
                BayTemperature = OvenController.BayTemperature,
                CPUUsage = OvenController.CPULoad.LoadPercentage,
                MemUsage = OvenController.FreeMem,
                Running = false,
                RunTime = -1,
                DoorOpen = OvenController.DoorAjar
            };
            SetJsonResult(Data);
        }

        public class JsonData
        {
            public float OvenTemperature{get; set;}
            public float BayTemperature { get; set; }
            public uint MemUsage { get; set; }

            public int CPUUsage { get; set; }
            public int RunTime { get; set; }

            public bool Running { get; set; }
            public bool DoorOpen { get; set; }
        }
    }
}
```

**Comment by Rinsen** [comment] 2015-04-02 19:35
Hi!

I have made a fix for this tha i will commit tomorrow. The problem is that the json serializer has a very basic type support for built in C# types and i have added some more type handling but I need to test this a bit more before it´s good enough to use.

So i will get back when it´s done.

**Comment by Rinsen** [comment] 2015-04-03 08:49
I have commited this change now and it should fix you´re problems.

One thing to remember is that the default C# stringbuilder float parser gives garbage back, in a perfect world this should be customizable in some way but right now it´s not. For an example you can check the test i have added that´s called WhenSerializeWithMoreDatatypes_GetSerialiedJsonString.

**Comment by Rinsen** [comment] 2015-04-03 08:51
And i also changed bool serializing to be only lower case letters in json data object to follow common json standards.

**Closed as completed** 2015-04-19 19:18 UTC
